training:
  algorithm: "ppo"       # "ppo" or "sac"
  timesteps: 100000
  save_dir: "trained_models"
  log_dir: "logs"
  save_freq: 10000
  device: "auto"         # "cuda" or "cpu"
  eval_episodes: 10

environment:
  max_steps: 1000
  num_lidar_rays: 16

model:
  learning_rate: 0.0003
  batch_size: 64
  gamma: 0.99
  
  # PPO parammeters
  n_steps: 2048
  ent_coef: 0.01
  
  # SAC parammeters
  buffer_size: 100000
  tau: 0.005

map:
  width: 100
  height: 100
  safety_margin: 1.0
  start: [10.0, 10.0]
  goal: [90.0, 90.0]
  
  # TEMPLATE FOR TRAINING: "easy", "medium", "hard", "maze". if 'custom', use obstacles below
  train_template: "hard" 
  
  train_obstacles:
    - type: "rectangle"
      x: 30
      y: 35
      width: 60
      height: 4
      angle: 0.0

    - type: "rectangle"
      x: 70
      y: 65
      width: 60
      height: 4
      angle: 0.0

    - type: "circle"
      x: 40
      y: 15
      radius: 3

    - type: "circle"
      x: 80
      y: 35
      radius: 2

    - type: "circle"
      x: 50
      y: 50
      radius: 4

    - type: "circle"
      x: 20
      y: 65
      radius: 2

    - type: "circle"
      x: 75
      y: 85
      radius: 3


  # TEMPLATE FOR EVALUATE: "easy", "medium", "hard", "maze". if 'custom', use obstacles below
  
  eval_obstacles:
    - type: "rectangle"
      x: 30
      y: 35
      width: 60
      height: 4
      angle: 0.0

    - type: "rectangle"
      x: 70
      y: 65
      width: 60
      height: 4
      angle: 0.0

    - type: "circle"
      x: 40
      y: 15
      radius: 3

    - type: "circle"
      x: 80
      y: 35
      radius: 2

    - type: "circle"
      x: 50
      y: 50
      radius: 4

    - type: "circle"
      x: 20
      y: 65
      radius: 2

    - type: "circle"
      x: 75
      y: 85
      radius: 3