training:
  algorithm: "ppo"                    # "ppo" or "sac"
  timesteps: 100000                   # timesteps for training
  save_dir: "trained_models"
  log_dir: "logs"
  save_freq: 10000
  device: "cpu"                       # "cuda" or "cpu"
  eval_episodes: 10

simulation:
  screen_width: 800
  screen_height: 800
  dt: 0.1

vehicle:
  length: 4.0
  width: 2.0
  wheelbase: 2.5
  max_velocity: 5.0
  max_acceleration: 3.0
  max_deceleration: -5.0
  max_steering_angle: 0.6

environment:
  max_steps: 10000
  num_lidar_rays: 16

model:
  learning_rate: 0.0003
  batch_size: 64
  gamma: 0.99
  
  # PPO parammeters
  n_steps: 2048
  ent_coef: 0.01
  
  # SAC parammeters
  buffer_size: 100000
  tau: 0.005

map:
  train_map_yaml_folder: 'maps/yaml'

  evaluate_map_yaml_file: 'maps/yaml/map_1.yaml'