training:
  algorithm: "ppo"       # "ppo" or "sac"
  timesteps: 100000
  save_dir: "trained_models"
  log_dir: "logs"
  save_freq: 10000
  device: "auto"         # "cuda" or "cpu"
  eval_episodes: 10

simulation:
  screen_width: 800
  screen_height: 800
  dt: 0.1

vehicle:
  length: 4.0
  width: 2.0
  wheelbase: 2.5
  max_velocity: 5.0
  max_acceleration: 3.0
  max_deceleration: -5.0
  max_steering_angle: 0.6 # ~34 degrees

environment:
  max_steps: 1000
  num_lidar_rays: 16

model:
  learning_rate: 0.0003
  batch_size: 64
  gamma: 0.99
  
  # PPO parammeters
  n_steps: 2048
  ent_coef: 0.01
  
  # SAC parammeters
  buffer_size: 100000
  tau: 0.005

map:
  width: 100
  height: 100
  safety_margin: 1.0
  start: [10.0, 10.0]
  goal: [90.0, 90.0]
  
  train_map_json: 'maps/yaml' # SET JSON WILL IGNORE TEMPLATE BELOW
  # TEMPLATE FOR TRAINING: "easy", "medium", "hard", "maze". if 'custom', use obstacles below
  train_template: "custom" 
  
  train_obstacles:
    - {type: rectangle, x: 15.0, y: 25.0, width: 30.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 25.0, y: 15.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 5.0, width: 30.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 15.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 75.0, y: 30.0, width: 10.0, height: 20.0, angle: 0.0}
    - {type: rectangle, x: 95.0, y: 5.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 95.0, y: 40.0, width: 10.0, height: 40.0, angle: 0.0}
    - {type: rectangle, x: 50.0, y: 35.0, width: 40.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 55.0, width: 70.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 15.0, y: 50.0, width: 10.0, height: 20.0, angle: 0.0}
    - {type: rectangle, x: 5.0, y: 75.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 35.0, y: 65.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 75.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 75.0, y: 75.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 95.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 30.0, y: 85.0, width: 20.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 75.0, y: 85.0, width: 10.0, height: 10.0, angle: 0.0}


  # TEMPLATE FOR EVALUATE: "easy", "medium", "hard", "maze". if 'custom', use obstacles below
  map_json: 'maps/generated_map.yaml' # SET JSON WILL IGNORE TEMPLATE BELOW
  eval_template: "custom"
  
  eval_obstacles:
    - {type: rectangle, x: 15.0, y: 25.0, width: 30.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 25.0, y: 15.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 5.0, width: 30.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 15.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 75.0, y: 30.0, width: 10.0, height: 20.0, angle: 0.0}
    - {type: rectangle, x: 95.0, y: 5.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 95.0, y: 40.0, width: 10.0, height: 40.0, angle: 0.0}
    - {type: rectangle, x: 50.0, y: 35.0, width: 40.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 55.0, width: 70.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 15.0, y: 50.0, width: 10.0, height: 20.0, angle: 0.0}
    - {type: rectangle, x: 5.0, y: 75.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 35.0, y: 65.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 75.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 75.0, y: 75.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 55.0, y: 95.0, width: 10.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 30.0, y: 85.0, width: 20.0, height: 10.0, angle: 0.0}
    - {type: rectangle, x: 75.0, y: 85.0, width: 10.0, height: 10.0, angle: 0.0}